### ISSUE TITLE
AzureAD giving the following error AADSTS65001

### ISSUE THREAD

**Issue by thonydy** [cradle77/Blazor.Msal#14]
The user or administrator has not consented to use the application with ID 'X' named 'X'. Send an interactive authorization request for this user and resource.

Do you know how I can handle this using Blazor Msal ?

**Comment by cradle77** [comment]
Hi, are you running the scripts and creating the app registration in your tenant?

**Comment by thonydy** [comment]
No, I'm not the admin of the application, so the tenant and all the information has been given to me by the admin. However, he is asking me to handle this error before giving me the consent, but I have no clue on how to handle it using Blazor Msal.

My appsettings.json contains : 
"Authority" : "https://login.microsoftonline.com/{tenant-id}
"ClientId" : "{client-id]"

**Comment by thonydy** [comment]
Sorry I have been completely not clear on what am I asking. My problem is more how can I catch this exception to be displayed on a layout rather than on console.
