### ISSUE TITLE
Pass extra options to loginRedirect & loginPopup

### ISSUE THREAD

**Issue by keesschollaart81** [cradle77/Blazor.Msal#15]
MSAL's JS SDK allows for some additional options in the login... methods, as documented here:

https://azuread.github.io/microsoft-authentication-library-for-js/docs/msal/modules/_authenticationparameters_.html

For example, I would like to be able to provide `extraScopesToConsent`

**Comment by cradle77** [comment]
Hello @keesschollaart81 ,

thanks for the feedback!

I'll add it to the backlog, it definitely makes sense to support these parameters. For now, the only option is using the "scopes" parameter, although not exactly the same thing!

I'll keep you posted!

**Comment by cradle77** [comment]
Hello! The new Blazor 3.2.0 preview 2 adds support for token based authentication
https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-2-release-now-available/

Therefore I think there's very little point in updating this project :)

Thanks a lot for having used it!
