### ISSUE TITLE
Getting Groups

### ISSUE THREAD

**Issue by hutchcodes** [cradle77/Blazor.Msal#17]
Trying to integrate this with AAD B2C. My understanding is that in order to get access to group information I'll need to call back to Microsoft Graph API. Is there an event I can listen for so I know when a user has authenticated so I can kick off that process?

**Comment by cradle77** [comment]
Hello Jeremy,

Azure AD B2C is not (yet) properly supported as it requires a couple of tricks. 

I’m actively working on it atm ;)

**Comment by cradle77** [comment]
Hello! The new Blazor 3.2.0 preview 2 adds support for token based authentication
https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-2-release-now-available/

Therefore I think there's very little point in updating this project :)

Thanks a lot for having used it!

**Comment by hutchcodes** [comment]
Just wanted to say thanks. Though it probably doesn't make sense to continue this project, it was was very helpful in understanding how authentication in Blazor could work.

**Comment by cradle77** [comment]
Thank you Jeremy! @hutchcodes
