### ISSUE TITLE
blazor.azuread.js not loading in Blazor WASM 3.2.0-preview1.20073.1

### ISSUE THREAD

**Issue by aletc1** [cradle77/Blazor.Msal#19]
Hi,

There might be an issue with the latest Blazor release and your library (BTW, very useful library).

![image](https://user-images.githubusercontent.com/14905652/75072081-083b9800-54f7-11ea-89f3-d4a73a98e0af.png)

## Workaround

I just copied the file blazor.azuread.js to my wwwroot and added this line to index.html:
```<script src="js/blazor.azuread.js"></script>```

**Comment by cradle77** [comment]
Hello! The new Blazor 3.2.0 preview 2 adds support for token based authentication
https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-2-release-now-available/

Therefore I think there's very little point in updating this project :)

Thanks a lot for having used it!
