### ISSUE TITLE
I do not do twitter.

### ISSUE THREAD

**Issue by multco-malan** [cradle77/Blazor.Msal#20]
"I'll be publishing a few articles on this topic. Follow me on twitter if you are interested and want to be notified when they are out."

I'm interested in any articles you have on this topic.

thanks for your work.

**Comment by cradle77** [comment]
Hello! The new Blazor 3.2.0 preview 2 adds support for token based authentication
https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-2-release-now-available/

Therefore I think there's very little point in updating this project :)

Thanks a lot for having used it!
