### ISSUE TITLE
Is this still a recommended approach now that Blazor client side is live?

### ISSUE THREAD

**Issue by jg11jg** [cradle77/Blazor.Msal#21]
Hi there this seems perfect for my needs - but just checking if in your opinion using this nuget is still the best way forward now that blazor WASM is out of preview.  If there is now a better way, could you share?

**Comment by cradle77** [comment]
Hello, Blazor WebAssembly now has official support for it, so I'd recommend to use that

**Comment by morganc9** [comment]
Hello,
Is it running with the last official blazor version?
The implementation of blazor msal doesn't allow the redirect option (pop-up only).
To me your lib could be a nice workaround until they implement the option...

**Comment by cradle77** [comment]
Hello Morgan,

I haven't ported it to the latest version, but I think you should be able to get it working without too much headache.

I wouldn't recommend it though, as definitely Microsoft's version is more stable than mine
